version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: geoevent-db
    restart: always
    environment:
      POSTGRES_PASSWORD: geoevent
      POSTGRES_DB: geoeventdb
    ports:
      - '5432:5432'
    volumes: 
      - db:/home/johan/hobby/GeoEvent/Geoevent-api/data/data
volumes:
  db:
    driver: local
